# Site settings
title: Shakti Rajpurohit
shortTitle: SR
tagline: "Hi, I am Shakti and this is my personal website. Here, you can check out my projects and social profiles."
url: "http://shakti.xyz"
baseUrl: "" # "/jekyll"

# Internal nav
nav:
  - Home: "/"
  - Projects: "/projects/"

social:
  Facebook: "www.facebook.com"
  LinkedIn: "www.linkedin.com"
  Instagram: "www.Instagram.com"

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
